### ISSUE TITLE
Percentage got stuck in 23%

### ISSUE THREAD

**Issue by tevas8** [confususs/whosThatColleague#1]
I kept getting (some) new faces and getting them right, but it was still stuck at 23%
Also, maybe unrelated, it decided to go back "Score: 0" at some point.
I might have left the browser tab unattended for 2 minutes so maybe it sort of timed out?
Edit: No, I just saw it going down to zero again after I clicked on some name.

**Comment by confususs** [comment]
> I kept getting (some) new faces and getting them right, but it was still stuck at 23%

The behavior indeed seems a bit vague. The 23% is associated with a score you had earlier. If you had 46 points the last time, you should beat it before the 23% will get higher again.

> Also, maybe unrelated, it decided to go back "Score: 0" at some point.

The score could go to zero when you decide to switch game modes in between. 

> Edit: No, I just saw it going down to zero again after I clicked on some name.

I did update the code somewhere after you posted this issue, so I hope you won't run into the situation where you click a correct name and it goes to 0%. :slightly_smiling_face: 

Before there was a situation where you could get the same name twice, once from voys & once from spindle. Clicking the wrong image + name combination would then put your score to 0. :stuck_out_tongue_winking_eye:
